ALTER TABLE Employee 
ADD City VARCHAR(20) NULL ;
GO

BEGIN TRANSACTION
UPDATE EMPLOYEE 
SET EMPNAME = 'Ali'
WHERE EmployeeId = 5

UPDATE EMPLOYEE
SET EMPNAME = 'Ali'
WHERE Mobile = 983333222

UPDATE EMPLOYEE
SET EMPNAME = 'Ali'
WHERE DepartmentId = 4

IF @@ROWCOUNT = 3
	COMMIT TRANSACTION
ELSE
	ROLLBACK TRANSACTION
;
GO

--COMMIT will change the data of a row in a table
BEGIN TRANSACTION
UPDATE EMPLOYEE SET Mobile = '987333222' WHERE EMPNAME= 'Ali';
COMMIT;
GO

--ROLLBACK will left unchange the data of row in a table
BEGIN TRANSACTION
	UPDATE EMPLOYEE SET DepartmentId= 3 WHERE EMPNAME = 'Ali';
ROLLBACK;