//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyTaskBotApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDailyReport
    {
        public int ID { get; set; }
        public string EmployeeName { get; set; }
        public string YesterdaysTask { get; set; }
        public string TodaysTask { get; set; }
        public string Obstacle { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
